options:
  platform: psp
  basename: w1_018
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/w1_018.bin
  asm_path: asm/pspeu/weapon/w1_018_psp
  asset_path: assets/weapon/w1_018
  src_path: src/weapon
  ld_script_path: build/pspeu/w1_018.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.w1_018.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.pspeu.w1_018.txt
  undefined_syms_auto_path: config/undefined_syms_auto.pspeu.w1_018.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  disassemble_all: true
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  global_vram_start: 0x08000000
  ld_generate_symbol_per_data_segment: true
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: 4f704060783e9066a8f1f5eb0cb8119269ba32a1
segments:
  - [0x0, bin, mwo_header]
  - name: w1_018
    type: code
    start: 0x80
    vram: 0x092F6C80
    bss_start_address: 0x092F7F00
    bss_size: 0x0
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, psp/w1_018]
      - [0xB80, data]
      - [0x1300, bss]
  - [0x1300]
