options:
  platform:     psx
  basename:     stmad
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/ST/MAD/MAD.BIN
  asm_path:     asm/us/st/mad
  asset_path:   assets/st/mad
  src_path:     src/st/mad
  ld_script_path: build/us/stmad.ld
  compiler:     GCC
  symbol_addrs_path:
    # NOTE: shifted overlay!
    - config/symbols.beta.txt
    - config/symbols.stmad.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.stmad.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.stmad.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  asm_jtbl_label_macro: jlabel
  extensions_path: tools/splat_ext
  string_encoding: SHIFT-JIS
  section_order:
    - ".data"
    - ".rodata"
    - ".text"
    - ".bss"
    - ".sbss"
segments:
  - name: stmad
    type: code
    start: 0x00000000
    vram:  0x80180000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .data, header]
      - [0xB8, .data, header] # layers
      - [0x290, data]
      - [0x2F4, .data, e_laydef] # layout entries header
      - [0x49C, data]
      - [0x6DC, .data, collision]
      - [0x9D4, .data, e_red_door]
      - [0x9EC, data]
      - [0xE40, data]
      - [0xEF8, .data, entity_relic_orb]
      - [0xF5C, data]
      - [0x1130, .data, rooms]
      - [0x11D4, .data, e_layout] # layout entries data
      - [0x1D14, data]
      - [0x2078, .data, tile_data] # tile data
      - [0x4678, .data, tile_data] # tile definitions
      - [0xCAA8, data]
      - [0xD794, rodata]
      - [0xD7CC, .rodata, e_red_door] # EntityRedDoor
      - [0xD7E4, rodata]
      - [0xD83C, .rodata, 139E0]
      - [0xD85C, .rodata, 139E0] # EntityEquipItemDrop
      - [0xD874, .rodata, entity_relic_orb]
      - [0xD8AC, rodata]
      - [0xD8C0, .rodata, prim_helpers]
      - [0xD8C8, c]
      - [0xE964, c, st_update]
      - [0xEDB8, c, collision]
      - [0x10544, c, create_entity]
      - [0x110A8, c, e_red_door]
      - [0x11D3C, c]
      - [0x139E0, c]
      - [0x149C0, c, entity_relic_orb]
      - [0x15520, c]
      - [0x18FA0, c, prim_helpers]
      - [0x197D8, sbss]
  - [0x19E94]
