options:
  platform: psp
  basename: w0_039
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/w0_039.bin
  asm_path: asm/pspeu/weapon/w0_039_psp
  asset_path: assets/weapon/w0_039
  src_path: src/weapon
  ld_script_path: build/pspeu/w0_039.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.w0_039.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.pspeu.w0_039.txt
  undefined_syms_auto_path: config/undefined_syms_auto.pspeu.w0_039.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  disassemble_all: true
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  global_vram_start: 0x08000000
  ld_generate_symbol_per_data_segment: true
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: 83825c26d13d102ff2245dd06f40b6a71ed58509
segments:
  - [0x0, bin, mwo_header]
  - name: w0_039
    type: code
    start: 0x80
    vram: 0x092F2E80
    bss_start_address: 0x092F4B80
    bss_size: 0x100
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, psp/w0_039]
      - [0xF00, data]
      - [0x1D80, bss]
  - [0x1E80]
